from os import environ

MQTT_DATA_TOPIC = environ["MQTT_DATA_TOPIC"]
MQTT_ALARM_TOPIC = environ["MQTT_ALARM_TOPIC"]
MQTT_SERVER_ADDRESS = environ["MQTT_SERVER_ADDRESS"]
MQTT_SERVER_PORT = int(environ["MQTT_SERVER_PORT"])

INFLUX_ADDRESS = environ["INFLUX_ADDRESS"]
INFLUX_PORT = environ["INFLUX_PORT"]
INFLUX_USER = environ["INFLUX_USER"]
INFLUX_TOKEN = environ["INFLUX_TOKEN"]
INFLUX_ORG = environ["INFLUX_ORG"]
INFLUX_BUCKET = environ["INFLUX_BUCKET"]
